### ISSUE TITLE
Hexágonos sem população e com renda no 10º decil

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/acesso_oport#103]
Esse hexágono tem população = 0, renda total = 23 e consequentemente renda per capita = Inf. Ele é classificado como 10º decil, o que não afeta os cálculos porque ele é ponderado pela população, que é zero. Mas ainda pode afetar os mapas de distribuição de decis.

![image](https://user-images.githubusercontent.com/1557047/130484624-c17e4b2e-e221-4bf4-a806-5c7f789a3503.png)

O que fazer?

**Comment by rafapereirabr** [comment]
O estranho é o hexagono ter ficado com pop 0 e renda total !=0. Não ? Idealmente precisaria de alguma correção na funcao de reaportion que corrige o problema na raiz.

**Comment by kauebraga** [comment]
Esses testes indicam q ta tudo OK

https://github.com/ipeaGIT/acesso_oport/blob/e91f70dacd81aea43fac9bee055c28ae39bd7523/R/03.3-agrupamento_das_variaveis_por_hexagonos.R#L326

```r
> hex_junto[pop_total == 0 & renda_total > 0]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
> hex_junto[pop_total == 0 & (quintil != 0)]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
> hex_junto[pop_total == 0 & (decil != 0)]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
> hex_junto[pop_total > 0 & renda_total == 0]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
> hex_junto[pop_total > 0 & idade_0a5 + idade_6a14 + idade_15a18 + idade_19a24 + idade_25a39  + idade_40a69 + idade_70 == 0]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
> hex_junto[pop_total > 0 & cor_branca + cor_amarela + cor_indigena + cor_negra == 0]
Empty data.table (0 rows and 40 cols): id_hex,h3_resolution,geometry,sigla_muni,ano,cor_branca...
```
