### ISSUE TITLE
O que fazer com hexágonos que têm renda mas não têm nem oportunidades nem empregos?

### ISSUE THREAD

**Issue by dhersz** [ipeaGIT/acesso_oport#104]
Meio relacionado ao https://github.com/ipeaGIT/acesso_oport/issues/103.

O hexágono destacado não tem nem empregos nem oportunidades, mas é utilizado no roteamento porque tem renda (23 reais). Isso provavelmente é resultado de algum join espacial entre as bases da grade estatística e dos setores censitários.

Hexágonos como esse devem ser considerados no roteamento? Ou não?

**Comment by kauebraga** [comment]
Acho que esses hexagonos devem ter a renda zerada. E vcs?

**Comment by rafapereirabr** [comment]
O estranho é o hexagono ter ficado com pop 0 e renda total !=0. Não ? Idealmente precisaria de alguma correção na funcao de reaportion que corrige o problema na raiz. Isso seria melhor do que zerar a renda a posteriori

**Comment by kauebraga** [comment]
Recentemente corrigi um erro la no reaportion (ele tava contando repetidamente a populacao de cada pedaco da grade), e o problema nao esta mais ocorrendo.
![image](https://user-images.githubusercontent.com/22420248/146942568-3bc29e73-761c-44bf-9882-d6e208763198.png)

**Comment by rafapereirabr** [comment]
maravilha. Com isso acho q podemos fechar os issues #103 e #104. Que acha @dhersz  ?

**Comment by dhersz** [comment]
parece ótimo!

**Comment by rafapereirabr** [comment]
@kauebraga , vamos deixar pra vc o prazer de feixar os issues entao ;)
