### ISSUE TITLE
tt_median not declared in script 5.1

### ISSUE THREAD

**Issue by szaszak** [ipeaGIT/acesso_oport#111]
Hi there,

Thanks for the awesome work! The reason I write is because I'm re running all the scripts and the variable 'tt_median' is present but not declared in script 5.1. 

I see that it is declared in a previous script 5 in [here](https://github.com/ipeaGIT/acesso_oport/blob/master/R/temp_rmds/05_acessibilidade.Rmd) - is it the same or has it passed substantial changes?

Thanks in advance

**Comment by kauebraga** [comment]
Hi @szaszak ! This script has changed a lot in the past few days, but I haven't pushed the modifications yet. I believe in the next commit everything should be just fine. Thanks for the heads up!

**Comment by kauebraga** [comment]
0f11b73223f1ae5c2106a1b22bb90b35b088a57f should do it. Thanks again!
