### ISSUE TITLE
Various land use checks to be done / fixed

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#121]
Goiania
1.	~~Dados de uso do solo para goiania só mostra RM em 2019. Em 2017 e 2018 aparece só o municípios~~ [isso aconteceu pq só tinha GTFS em 2019, e os dados de 2017 e 2018 da RM nao foram geocoded; Isso vai ficar assim nesta edicao]

2.	~~Em 2019, tem uma célula com 9 hospitais (8 de media complexidade)~~ [Isso vai ficar assim nesta edicao]
3.	Colocando acesso a empregos em 120 minutos por PT dá pra ver muitos problemas de snap [isso deve ser diminuido com nova matrix auxmentando o tempo de acesso ao PT]

Brasilia
1.	Tem célula com 22+ escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas
Rio
1.	tem célula com 7 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

São Goncaçlo
1.	tem célula com 6+ escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

São Paulo
1.	tem célula com 5 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

São Luiz
1.	tem célula com 5 hospitais em todos os anos. Checar se o script está puxando os dados de escolas corrigidas
2.	tem célula com 6 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

Manaus
1.	tem célula com 6 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

Recife
1.	tem célula com 5 hospitais em todos os anos. Checar se o script está puxando os dados de escolas corrigidas
2.	tem célula com 5 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

Natal
1.	tem célula com 7 hospitais em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

Maceio
1.	tem célula com 6 escolas em todos os anos. Checar se o script está puxando os dados de escolas corrigidas

**Comment by kauebraga** [comment]
A maioria dos casos esta OK, precisando só de alguns ajustes pontuais de localização dos estabelecimentos. Nesses casos, vou usar o nome da escola/hospital, quando possível. Mas estamos utilizando todas as bases corretas pra trazer as atividades pro hexágonos.
O principal problema ai eh Brasilia. A gente mudou o critério pra aceitar a qualidade do estabelecimentos depois de ter feito grande parte das checagens (aceitamos as categorias 'political' e 'postal_code' somente pra bsb), por isso que esse caso acabou passando batido. Nesse caso, também vou usar o nome escola pra tentar melhorar a localização. https://github.com/ipeaGIT/acesso_oport/blob/e91f70dacd81aea43fac9bee055c28ae39bd7523/R/fun/filter_geocode.R#L90

**Comment by kauebraga** [comment]
Done at https://github.com/ipeaGIT/acesso_oport/commit/ecb3d114d6709d33628454ee6ff3e094a15e855d
