### ISSUE TITLE
Definir tipos de estabelecimentos de saude

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#13]
- Limpas dados dos CNES
- Definir tipos de estabelecimento do CNES

**Comment by kauebraga** [comment]
Junto da base que a gente está utilizando, tem a base dos CNES Ativos, que está na mesma página: http://dados.gov.br/organization/5b283f30-ced3-4ccc-b44a-406e8a92e1ad?groups=saude

Nela, tem uma coluna ``ds_tipo_unidade``, que tem 37 tipos de unidade de saúde, indo desde clínica à unidade móvel fluvial. Dentro delas, dá pra identificar unidades que seriam do nosso interesse, como **centro de saude/unidade basica, unidade de apoio diagnose e terapia, posto de saúde, policlínica, hospital geral, pronto atendimento e pronto socorro geral.**

Essa base ativa não tem ``lon``e ``lat``, porém todos os estabelecimento que tem lá a gente tem na nossa base que tem as coordenadas completas (que é a que a gente tá utilizando agora).

**Comment by rafapereirabr** [comment]
Sim, a ideia é fazer o join das duas bases mesmo 

Rafael H.M. Pereira

**Comment by rafapereirabr** [comment]
feito usando base de dados unica do CNES de 2019
