### ISSUE TITLE
Aprimorar script de calculo de acessibilidade

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#14]

**Comment by kauebraga** [comment]
- [ ] Estabelecer uma coluna de hora para o arquivo de modos ativos para poder juntá-lo aos arquivos de transporte público;
- [ ] Adaptar código para data.table;
- [ ] Juntar todos os modos em um dt só;

**Comment by kauebraga** [comment]
Perguntas a serem consideradas:

- O time threshold deve mudar para cada cidade (em função do tamanho da cidade)?
-  O time threshold deve mudar para cada modo?

**Comment by rafapereirabr** [comment]
> Perguntas a serem consideradas:
> 
> * O time threshold deve mudar para cada cidade (em função do tamanho da cidade)?
> * O time threshold deve mudar para cada modo?

A gente ja esta calculando varios thresholds (30, 60, 90 min.). Vai ser uma analise combinatoria de calcular todos thresholds para todas cidades para todos os modos

**Comment by rafapereirabr** [comment]
- [ ] incluir calculo de medida cumulativa passiva (CMP)
- [ ] incluir calculo de medida competitiva (CPT)

**Comment by kauebraga** [comment]
Cálculo do indicador de acessibilidade passiva adicionado em https://github.com/ipeaGIT/acesso_oport/commit/b213165c874b6a2845ae3c3225d1348a00fd7830

**Comment by kauebraga** [comment]
O que falta nesse issue está incorporado em outro issue, que é a medida competitiva. Por isso fechando.
