### ISSUE TITLE
Corrigir outliers na localizalçao de empregos RAIS 2017

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#16]
Criar função a partir de `Limpeza_outliers_empregos_RAIS.R`

**Comment by kauebraga** [comment]
Cerca de 70% dos registros nas categorias que a gente quer excluir os outliers não tem nenhum vínculo, o que é bem estranho

**Comment by kauebraga** [comment]
Done. Salvo como arquivo  ``../data/rais/rais_2017_corrigido.csv``, que agora tem a coluna ``qt_vinc_ativos2`` com o número de vínculos corrigido pelo método. Não vou fechar ainda por conta da ressalva acima..

**Comment by rafapereirabr** [comment]
Conversou com a Vanessa sobre isso? Pelo o que me lembro de ter conversado com ela, isso não é problema. Tem mesmo um número grande de empresas sem vínculo e que temos q excluir da base 

Rafael H.M. Pereira

**Comment by kauebraga** [comment]
Testei o mesmo código para 2015, e a quantidade de estabelecimentos sem vínculo é baixa (menor que 90%). Vou tentar conversar com a Vanessa agora pra ver o que ela acha. E também procurar onde eu possa ter errado aqui rs

**Comment by kauebraga** [comment]
De 1.140 milhões de estabelecimentos (só aqueles a serem corrigidos), mais de 70% não tem registro

| qt_vinc_ativos|      n|
|--------------:|------:|
|              0| 798432|
|              1| 108956|
|              2|  52570|
|              3|  33163|
|              4|  22879|
|              5|  16407|
|              6|  12621|
|              7|   9877|
|              8|   8170|
|              9|   6515|

**Comment by kauebraga** [comment]
Conversei com a Vanessa, e é isso mesmo.. o número alto de vínculos zero é esperado. A diferença pra base de 2015 foi grande porque nela já teve um pré-tratamento dos vínculos

**Comment by rafapereirabr** [comment]
Joia.

Rafael H.M. Pereira
