### ISSUE TITLE
Check method behind `friction surface' data by Weis et al (2018)

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#19]
Check whether the 'friction surface' data set produced by [Weis et al (2018) ](https://map.ox.ac.uk/research-project/accessibility_to_cities/) takes traffic congestion into account.

**Comment by kauebraga** [comment]
Should we close this one @rafapereirabr ?

**Comment by rafapereirabr** [comment]
I think we can :(
