### ISSUE TITLE
Rodar todas matrizes de tempo de viagem

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#2]
Usar script OTP parallel

**Comment by kauebraga** [comment]
Done! Passo a passo:

- Criada função ``selecionar_data_gtfs`` que seleciona uma data para o otp baseado no arquivo gtfs;
- Criada função ``criar_script_python_paral_modes`` que gera as funções em python em paralelo, para todos os modos, e para várias horas de partida;
- Ajustada a função ``aplicar_otp`` para rodar os scripts py em paralelo, para todos os modos e horários;
- Aplicada a função acima para as 6 cidades.

**Comment by rafapereirabr** [comment]
Maravilha. Ja rodou as matrizes considerando resolucao de ~ 350m? Tem ideia de quanto demorou no total?

**Comment by kauebraga** [comment]
Fortaleza, pra dois horário de partida, demorou cerca de 50 minutos.
