### ISSUE TITLE
implementar codigo para calcular muitas medidas de acessibilidade

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#28]
ver aqui: [https://stackoverflow.com/questions/57633073/pass-strings-as-code-to-summarize-multiple-columns-with-data-table/57634258#57634258](https://stackoverflow.com/questions/57633073/pass-strings-as-code-to-summarize-multiple-columns-with-data-table/57634258#57634258)

**Comment by kauebraga** [comment]
Resolvido em https://github.com/ipeaGIT/acesso_oport/commit/42e8cb4544110a1e8c2cc6e0f5700b1d2416e913. Falta adptar o resto do código para salvar a acessibilidade e criar os mapa

**Comment by kauebraga** [comment]
Done.
