### ISSUE TITLE
Checar de qualidade estimativas de access

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#3]
- Checar se output de ttmatrix inclui todas origens e destinos solicitados
- checagem visual de mapas com CUM access measure (jobs :=1)

**Comment by kauebraga** [comment]
Em suma, foram estabelecidas as funções para checar se o output do OTP inclui todas as origens e destinos (``avaliar_qualidade_otp``) e para checar a qualidade do indicador de acessibilidade (``avaliar_qualidade_acess``). Os resultados postados (no arquivo ``04_matriz.md``) foram uma tabela com as cidades e a quantidade de pontos que ficou fora da análise e os mapas de 4 cidades com a avaliação da acessibilidade. Mas entende-se que é melhor visualizar esses pontos espacialmente, caso a caso.

**Comment by rafapereirabr** [comment]
Filtrar hexagonos sem atividade antes de criar pontos para OTP

**Comment by rafapereirabr** [comment]
- Rodar função de `snap` para hexagonos com valor 0 
- Atualizar `lat long` dos centroides para pontos que foram feitos snap
- Rodar matrix de tempo de deslocamento
- fazer teste visual com mapas (CMA 90 min.)

**Comment by kauebraga** [comment]
Função foi aplicada e os pontos corrigidos estão sendo salvos na pasta ``../otp/points_corrigidos``
