### ISSUE TITLE
Shinny App not running

### ISSUE THREAD

**Issue by orlando-sabogal** [ipeaGIT/acesso_oport#30]
Fantastic work! I am thrilled with this repo.

I am not able to run the shinny in `setwd("apps/app_bootstrap_style/")`

I get the following error: 

**cannot open compressed file '../../../data/linhas_HMcapacidade/linhas_HMcapacidade.rds', probable reason 'No such file or directory'**

In the line 27 of the server function you have:

`linhas <- read_rds("../../../data/linhas_HMcapacidade/linhas_HMcapacidade.rds")`

So it seems like **"linhas_HMcapacidade.rds"** is on your local computer but not in the repo. 

Or am I missing something?

**Comment by rafapereirabr** [comment]
Hi Orlando. Thanks for the kind words!

That's correct. The file `linhas_HMcapacidade.rds` is not available on the github repository. Hence the error. If you comment the rows that call this file (and a few others we store locally), the shiny app should run.

In any case, we are still making lots of updates to the data analyses. As of today the results in this repo are only preliminary test results. As soon as we have the final results we'll fix this issue.

**Comment by rafapereirabr** [comment]
We have moved the shiny interactive map to this repo: https://github.com/ipeaGIT/acesso_app

Closing this issue
