### ISSUE TITLE
Definir plataforma de compartilhamento dos dados

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#40]
## Opções
1) [Havard Dataverse](https://dataverse.harvard.edu/)
1) [Figshare](https://figshare.com/account/home)
1) [Figshare](https://figshare.com/account/home) (só metadados como o DOI) + Github (hospedagem dos dados)

A viabilidade do 3. vai depender do tamanho da base de dados

## Pontos a considerar
- Gera DOI;
- Tem API com R através de algum pacote;
- Pode linkar com algum paper;
- Pode ligar a base com um outro site (através de widgets);
- Tem suporte para markdown ou HTML.

**Comment by rafapereirabr** [comment]
compartilhando dados pelo repositorio do Ipea
