### ISSUE TITLE
Future corrections

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#41]
Script 02.3

- [x] Concertar celulas com renda per capita `Inf`
- [x] substituir 'capta' por 'capita'

**Comment by rafapereirabr** [comment]
- [ ] reestruturar codigo do projeto para acomodar dados de input/output para diferentes anos

**Comment by SymbolixAU** [comment]
a very minor tweak [here](https://github.com/ipeaGIT/acesso_oport/blob/master/apps/app_bootstrap_style/server.R#L159)

```r
      # create viridis scale in the reverse direction
      # create matrix
      colorss <- colourvalues::color_values_rgb(x = 1:256, "viridis")
      # invert matrix
      colorss <- apply(colorss, 2, rev)
```

can be replaced with

```r
colourvalues::get_palette("viridis")[256:1, ]
```

**Comment by kauebraga** [comment]
Thanks @SymbolixAU!
The shinyapp code available here is very outdated though.
We are developing the shinyapp available on the [site](https://www.ipea.gov.br/acessooportunidades/en/) in  [other repository](https://github.com/ipeaGIT/acesso_app).
