### ISSUE TITLE
Paper on inequalities in access to health services

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#44]
The racial and economic inequalities in access to health services in Brazil"

- [ ] draft of paper outline

**Comment by kauebraga** [comment]
https://www.journals.elsevier.com/journal-of-transport-and-health/call-for-papers/health-equity-social-inclusion-and-mobility

**Comment by kauebraga** [comment]
Should we make a final effort on this one? 1 week left!
I can (at least try to) go full time..

**Comment by rafapereirabr** [comment]
Closing this issues means you gave up on the paper entirely? or only gave up on that special issue deadline? ;)

**Comment by kauebraga** [comment]
Only on the special issue!
