### ISSUE TITLE
update street network for 2020

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#55]
two alternatives to download OSM .pbf direclty from R

- [osmextract](https://github.com/ITSLeeds/osmextract)
- [geofabrik](https://github.com/ibarraespinosa/geofabrik)

**Comment by mvpsaraiva** [comment]
we can download the pbf file for the entire country, save it in our server, and then call a command line tool such as Osmosis from R to extract data for each city.

[Preparing a baseline transport network](http://docs.analysis.conveyal.com/en/dev/prepare-inputs/index.html#cropping)

**Comment by rafapereirabr** [comment]
If you know a simple way to corp a .pbf from within R that would be great! Do you know how to do this? If so, perhaps this is a function we could add to r5r ?

**Comment by kauebraga** [comment]
Any updates on this?

**Comment by mvpsaraiva** [comment]
Fiz um script pra extrair a rede viária de cada cidade do PBF do Brasil inteiro. Pra isso, tive que baixar o executável do Osmosis e salvar lá na pasta do projeto. Fiz um pull request com o script.

**Comment by rafapereirabr** [comment]
Maravilha!!! Valeu @mvpsaraiva . Isso ajuda muito. Para uma solução mais leve (que nao requer baixar o .pbf de todo país), a gente podia tentar usar o novo pacote [osmextract](https://github.com/ropensci/osmextract).

**Comment by mvpsaraiva** [comment]
> Para uma solução mais leve (que nao requer baixar o .pbf de todo país), a gente podia tentar usar o novo pacote [osmextract](https://github.com/ropensci/osmextract).

O problema do osmextract é que, até onde eu sei, ele não permite baixar a bounding box de cada cidade. Teríamos que delimitar as redes ao limite exato de cada município. Tem também a questão das regiões metropolitanas... Mas enfim, podemos tentar melhorar e também reduzir o tamanho dos pbf's gerados, pois alguns ficaram bem grandes.

**Comment by rafapereirabr** [comment]
@mvpsaraiva , acho que podemos fechar esse issue, neh?

**Comment by mvpsaraiva** [comment]
Quase... estou testando um código pra filtrar os polígonos do pbf pros arquivos ficarem menores. Só falta verificar se os arquivos reduzidos ainda têm todas informações necessárias pro roteamento, ou se eu filtrei algo a mais.

**Comment by mvpsaraiva** [comment]
> @mvpsaraiva , acho que podemos fechar esse issue, neh?

Feito o pull request. Já podemos fechar esse issue 👍

**Comment by rafapereirabr** [comment]
Joia! maravilha. E voce j atualizou os arquivos `.pbf` para 2020 na pasta `./data-raw/` ?

**Comment by mvpsaraiva** [comment]
> Joia! maravilha. E voce j atualizou os arquivos `.pbf` para 2020 na pasta `./data-raw/` ?

Sim, rodei os scripts e os arquivos já estão atualizados lá na `./data-raw/`

**Comment by rafapereirabr** [comment]
Maravilha! Valeu !
