### ISSUE TITLE
Comparison R5 x OTP

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#59]
- [x] Calculate R5 ttmatrix for the same period as OTP's were: 06:00 to 08;00 every 15 minutes
- [x] Check if there is something wrong with Rio and Sao Paulo;
- [ ] Possible cenario: use R5 for public transporte routing and `dodgr` for bike + walk (because it considers topo)

**Comment by rafapereirabr** [comment]
De certa maneira, essa comparaçao foi feita nesse [issue no r5r](https://github.com/ipeaGIT/r5r/issues/106). E como o R5 nao considera topografia, acabamos decidindo por continuar usando o OTP por enquanto.
