### ISSUE TITLE
TO do

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#60]
- [x] Run Rio's ttmatrix for 2019 with OTP without topography files;
- [x] Fix hex with jobs outliers from RAIS 2018;

**Comment by kauebraga** [comment]
## Run Rio's ttmatrix for 2019 with OTP without topography files

There is little difference between the ttmatrix estimated with the old topography file and the ttmatrix without a topography file, both by OTP. 

![image](https://user-images.githubusercontent.com/22420248/96724084-d0d30300-1385-11eb-9baa-8bfc247a3e5f.png)

**Comment by rafapereirabr** [comment]
This is the travel time matrix by cycling? or walking?

**Comment by kauebraga** [comment]
This is by public transport, so we could compare OTP and R5 properly. Marcus may have updates on the active modes :)

**Comment by kauebraga** [comment]
Should we close this one?

**Comment by rafapereirabr** [comment]
Yep. We can close this one
