### ISSUE TITLE
Comparação entre roteadores #1: Snap no ponto de origem

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/acesso_oport#61]
Esta análise mostra como o algoritmo de _snap_ das coordenadas lat/long no sistema viário pode gerar um efeito em cascata nos resultados do roteamento.

A imagem abaixo mostra uma célula hexagonal e suas 7 células "filhas" em uma área de rede viária esparsa em Belo Horizonte:
![image](https://user-images.githubusercontent.com/7387691/97469518-42cabf80-1925-11eb-9d5f-d561d1f6030e.png)

Usando cada uma dessas filhas como ponto de partida, obtemos as seguintes áreas alcançáveis em até 120 min de viagem, usando o R5:

![image](https://user-images.githubusercontent.com/7387691/97469839-9b9a5800-1925-11eb-9288-5910015ad0c1.png)

**Comment by rafapereirabr** [comment]
Marcus, obrigado pela analise. Dá para ver que em alguns casos o snap vai 'dar ruim' e que é dificil prever de antemao quando isso pode acontecer. Como a gente conversou na reuniao com a equipe, a solução que vamos adotar é fazer um pós-processamento nas analises de acessibilidade para minimizar alguns pontos que fiquem como outlier comparado aos seus vizinhos.
