### ISSUE TITLE
Comparação entre roteadores #2: efeito da topografia nas viagens a pé e de bicicleta

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/acesso_oport#62]
Comparei os roteadores R5 (sem topografia), OpenTripPlanner (com topografia) e dodgr (com e sem topografia), na cidade de Belo Horizonte.

Considerando os 3 pontos de partida abaixo (pontos vermelhos):
![image](https://user-images.githubusercontent.com/7387691/97470467-50cd1000-1926-11eb-91bd-1332316a8194.png)

**Comment by mvpsaraiva** [comment]
No roteamento por bicicleta, pode-se notar como as áreas alcançáveis são muito maiores quando a topografia é desconsiderada (R5 e dodgr_flat). Nas duas simulações em que a topografia é levada em consideração, é visível uma pequena diferença entre os resultados do dodgr e do OTP: parece que o OTP atribui um peso um pouco maior para a topografia, o que gera áreas acessíveis um pouco menores.
![image](https://user-images.githubusercontent.com/7387691/97470566-6cd0b180-1926-11eb-8787-7f7bd7c0d307.png)

**Comment by mvpsaraiva** [comment]
No roteamento a pé, quase não se nota diferença entre dodger com e sem elevação e o R5, enquanto a ponderação do OTP apresenta um efeito significativo nos resultados.
![image](https://user-images.githubusercontent.com/7387691/97471564-9fc77500-1927-11eb-94b4-7fa1b97b7b3f.png)

**Comment by mvpsaraiva** [comment]
O dodgr usa a regra de Naismith (https://en.wikipedia.org/wiki/Naismith%27s_rule) para fazer a ponderação da topografia nas viagens a pé. Pelo que notei, essa regra gera diferenças bem sutis nos tempos de viagem. O Mark Padgham está considerando adicionar outras regras de ponderação no dodger: https://github.com/ATFutures/dodgr/issues/124

Os desenvolvedores do OTP implementaram funções mais robustas, conforme os issues abaixo:
https://github.com/opentripplanner/OpenTripPlanner/issues/2579
https://github.com/opentripplanner/OpenTripPlanner/pull/2580

**Comment by rafapereirabr** [comment]
Síntese:

- O dodgr e OTP tem resultados bem semelhantes quando consideram topografia
- Quando se ignora a topografia, os resultados do dodgr e R5 ficam bem parecidos
- Desconsiderar a topografia tende a sobre-estimar o nível de acessibilidade

**Comment by mvpsaraiva** [comment]
Novas estimativas com o R5, agora com topografia e diferentes níveis de LTS.

### Por bicicleta

Há alguns problemas de descontinuidade no R5 LTS 4 q parecem bug (vou checar depois), mas fora isso o OTP é muito parecido com o R5 LTS 4. Em termos práticos, acho que faz mais sentido usar o R5 com LTS = 3, porque o LTS 2 me parece restritivo demais, inclusive com resultado quase igual ao LTS 1.

<img width="1370" alt="Screenshot 2021-05-11 at 18 38 22" src="https://user-images.githubusercontent.com/7387691/117888158-1acef800-b288-11eb-8a3a-e4b4686ee0f4.png">


### A pé

Aqui a diferença é menos visível, mas dá pra ver que as áreas do R5 flat são maiores que as outras.

<img width="763" alt="Screenshot 2021-05-11 at 20 42 32" src="https://user-images.githubusercontent.com/7387691/117897918-2aefd300-b29a-11eb-823b-4f7c73a68317.png">

**Comment by rafapereirabr** [comment]
ótimo! Sim, o resultado do OTP parece mais com o LTS 4 do r5r. Mas aqueles bugs ali estão meio estranhos mesmo rsrsrsrs

**Comment by mvpsaraiva** [comment]
> Muito bom @mvpsaraiva. O `r5r_flat` no caso das bicicletas é LTS 4 sem topografia?

Exato... LTS 4.

**Comment by mvpsaraiva** [comment]
> ótimo! Sim, o resultado do OTP parece mais com o LTS 4 do r5r. Mas aqueles bugs ali estão meio estranhos mesmo rsrsrsrs

Pois é, esses bugs estavam muito estranhos mesmo hehe. Então eu rodei tudo de novo com um pbf novo e o problema sumiu. Novos mapas abaixo:

<img width="1380" alt="Screenshot 2021-05-12 at 10 38 28" src="https://user-images.githubusercontent.com/7387691/117984448-3c72c280-b30e-11eb-9de3-d55739b789d2.png">

Tinha algum bug naquele pbf antigo, parece que tem alguma "conexão invisível" entre as bordas do mapa. Imagino q alguns edges com comprimento negativo também podem causar esse tipo de problema.

O pbf novo foi gerado com aquele script do Osmosis q eu fiz um tempo atrás, então já serviu pra testar a qualidade deles.

**Comment by mvpsaraiva** [comment]
Testando a diferença da acessibilidade uniforme (1 emprego por hexágono) entre os roteadores. Nos mapas abaixo, azul (valores positivos) significa que a acessibilidade calculada pelo R5 é maior q a do OTP, enquanto vermelho significa o contrário.

No geral, dá pra notar que os valores calculados por R5 e OTP estão muito mais próximos, quando se considera a topografia em ambos.

### Bicicleta

<img width="901" alt="Screenshot 2021-05-12 at 11 33 25" src="https://user-images.githubusercontent.com/7387691/117993892-81025c00-b316-11eb-91ed-cbb048a59afe.png">

### A pé

<img width="1092" alt="Screenshot 2021-05-12 at 11 37 02" src="https://user-images.githubusercontent.com/7387691/117993936-8a8bc400-b316-11eb-8865-8575ef4f6330.png">

**Comment by mvpsaraiva** [comment]
Algumas estatísticas.

MAE - Mean Absolute Error
RMSE - Root Mean Squared Error

### Bicicleta

| tempos de viagem |      |      |
|------------------|------|------|
| engine           | MAE  | RMSE |
| r5_elev_lts1     | 17.9 | 20.6 |
| r5_elev_lts2     | 17.3 | 19.9 |
| r5_elev_lts3     | 11.2 | 13.5 |
| **r5_elev_lts4**     | **5.59** | **7.51** |
| r5_flat          | 19.8 | 21.7 |

| acessibilidade |      |      |
|----------------|------|------|
| engine         | MAE  | RMSE |
| r5_elev_lts1   | 575. | 629. |
| r5_elev_lts2   | 551. | 602. |
| r5_elev_lts3   | 358. | 398. |
| **r5_elev_lts4**   | **78.9** | **122.** |
| r5_flat        | 896. | 917. |

### A pé

| tempos de viagem |      |      |
|------------------|------|------|
| engine           | MAE  | RMSE |
| **r5_elev**          | **2.63** | **4.09** |
| r5_flat          | 5.20 | 6.26 |

| acessibilidade   |      |      |
|------------------|------|------|
| engine           | MAE  | RMSE |
| **r5_elev**          | **11.5** | **16.4** |
| r5_flat          | 38.5 | 43.1 |

**Comment by rafapereirabr** [comment]
@mvpsaraiva , Essas medidas de 'erro' são em comparação ao OTP. Certo?

**Comment by mvpsaraiva** [comment]
> @mvpsaraiva , Essas medidas de 'erro' são em comparação ao OTP. Certo?

Exato... o OTP é o ponto de referência em todos os cálculos.

**Comment by rafapereirabr** [comment]
Por todas análises acima, eu sugiro que o valor default do LTS no r5r seja 4. O que acham?

**Comment by dhersz** [comment]
É o que mais se assemelha ao comportamento do OTP, mas será que o comportamento do OTP é o que a gente julga o mais adequado? :)

Até onde eu lembro das nossas conversas passadas, o LTS 4 era muito permissivo com as rotas que um ciclista poderia utilizar. O Marcus comentou que o 2 é muito restritivo, e pode não fazer sentido no contexto brasileiro.

De fato, copiando [desse comentário aqui](https://github.com/ipeaGIT/r5r/issues/160#issuecomment-816217800) no issue do r5r, talvez uma grande parte parte dos ciclistas brasileiros se encaixe na definição de entusiastas e confiantes.

> * LTS 1: **Tolerable for children**. This includes low-speed, low-volume streets, as well as those with separated bicycle facilities (such as parking-protected lanes or cycle tracks).
> * LTS 2: **Tolerable for the mainstream adult population**. This includes streets where cyclists have dedicated lanes and only have to interact with traffic at formal crossing.
> * LTS 3: **Tolerable for “enthused and confident” cyclists**. This includes streets which may involve close proximity to moderate- or high-speed vehicular traffic.
> * LTS 4: **Tolerable for only “strong and fearless” cyclists**. This includes streets where cyclists are required to mix with moderate- to high-speed vehicular traffic.

O 4 realmente me parece inadequado, dada essa descrição, e fico com a impressão que o 2 e o 3 são mais adequados pra um estudo na escala urbana. Remotando ao trabalho do Antonio Paez sobre acessibilidade positiva e normativa, me parece que utilizar o LTS 3 seria mais "positivo", já que se assemelharia mais ao comportamento dos ciclistas brasileiros, enquanto o LTS 2 seria mais "normativo", por ser aproximar a uma situação tida como ideal.

**Comment by rafapereirabr** [comment]
> É o que mais se assemelha ao comportamento do OTP, mas será que o comportamento do OTP é o que a gente julga o mais adequado? :)
> 
> Até onde eu lembro das nossas conversas passadas, o LTS 4 era muito permissivo com as rotas que um ciclista poderia utilizar. O Marcus comentou que o 2 é muito restritivo, e pode não fazer sentido no contexto brasileiro.
> 
> De fato, copiando [desse comentário aqui](https://github.com/ipeaGIT/r5r/issues/160#issuecomment-816217800) no issue do r5r, talvez uma grande parte parte dos ciclistas brasileiros se encaixe na definição de entusiastas e confiantes.
> 
> > * LTS 1: **Tolerable for children**. This includes low-speed, low-volume streets, as well as those with separated bicycle facilities (such as parking-protected lanes or cycle tracks).
> > * LTS 2: **Tolerable for the mainstream adult population**. This includes streets where cyclists have dedicated lanes and only have to interact with traffic at formal crossing.
> > * LTS 3: **Tolerable for “enthused and confident” cyclists**. This includes streets which may involve close proximity to moderate- or high-speed vehicular traffic.
> > * LTS 4: **Tolerable for only “strong and fearless” cyclists**. This includes streets where cyclists are required to mix with moderate- to high-speed vehicular traffic.
> 
> O 4 realmente me parece inadequado, dada essa descrição, e fico com a impressão que o 2 e o 3 são mais adequados pra um estudo na escala urbana. Remotando ao trabalho do Antonio Paez sobre acessibilidade positiva e normativa, me parece que utilizar o LTS 3 seria mais "positivo", já que se assemelharia mais ao comportamento dos ciclistas brasileiros, enquanto o LTS 2 seria mais "normativo", por ser aproximar a uma situação tida como ideal.

Boa. Pensando por esse lado, eu concordo em passarmos o default para 3

**Comment by mvpsaraiva** [comment]
Estou em dúvida também. Em certo sentido, o LTS 4 parece mais "neutro", já que ele se aproxima mais do OTP e também do dodgr (olhando os mapas dos comentários mais antigos). Por outro lado, será que faz sentido assumir que um ciclista normal (tipo um estudante de ensino médio indo pra escola) vai pedalar pela marginal Tietê?  Minha tendência é concordar com a opinião do Daniel, de que LTS 3 faz mais sentido pro nosso estudo em escala urbana. 

Além disso, com LTS 3 nós podemos capturar melhorias na infra estrutura cicloviária de um ano pro outro. Por exemplo, com LTS 3, o ciclista vai evitar uma rodovia muito movimentada em um ano mas pode utilizar o mesmo trajeto em outro ano caso uma ciclovia seja implantada. Por outro lado, com LTS 4, o ciclista vai andar em meio ao tráfego pesado independente da existência da ciclovia.
