### ISSUE TITLE
Comparação entre roteadores #3: efeito da topografia nas viagens por transporte público

### ISSUE THREAD

**Issue by mvpsaraiva** [ipeaGIT/acesso_oport#64]
Comparei tempos de viagem e acessibilidade usando OpenTripPlanner com e sem topografia. A acessibilidade foi calculada com uma distribuição uniforme de oportunidades (1 por célula) e 60 minutos de tempo de viagem.

**Comment by rafapereirabr** [comment]
Síntese sobre a análise do **OTP**:
- Desconsiderar a topografia tende a sobre-estimar os tempos de viagens e o nível de acessibilidade
- A magnitude do efeito varia entre cidades, mas aponta para uma acessibilidade sobre-estimada em cerca de 10%-20% para uma quantidade razoável de hexagonos.

Síntese sobre a análise do **R5**:
- a versão atual do R5 desconsidera topografia e por isso sobrestima acessibilidade
