### ISSUE TITLE
Download maptile for Goiânia

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#73]

**Comment by kauebraga** [comment]
We forgot that Goiânia was already in the project...

**Comment by dhersz** [comment]
Doesn't this issue refer to downloading the maptile for the entire RM?

**Comment by kauebraga** [comment]
Putz, tem razão, foi mal haha Abrindo de novo..

**Comment by kauebraga** [comment]
Essa pode ser fechada aqui https://github.com/ipeaGIT/acesso_oport/commit/4af5687a5d757d1bbe4de7f102c4ddd24825f5fe
