### ISSUE TITLE
Incluir numero de matriculas por nível educacional

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#85]
Incluir numero de matricas por nivel educational em cada escola

**Comment by kauebraga** [comment]
Essa aqui vai dar mais trabalho do que eu imaginava. Na base de `escolas` do censo só tem a info se a escola tem ou não matrícula de cada nível. Vamos ter que na base de `matrículas`, que tem a matrícula de cada aluno, então agrupar por escola e pelo nível de ensino que o aluno tá e calcular o total. Atenção: temos 74 etapas de ensino..

**Comment by kauebraga** [comment]
Feito https://github.com/ipeaGIT/acesso_oport/commit/ae42e172b041cc52cad104ac3b9da433641a14af. Ainda precisa de alguns testes e depois adaptar o script `02.3`

**Comment by kauebraga** [comment]
Finished at https://github.com/ipeaGIT/acesso_oport/commit/4493251269667d7b789e63c115b84deebae66b53
