### ISSUE TITLE
Incorporar cálculo do CMP (cumulativa passiva) no script de acessibilidade

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#92]

**Comment by kauebraga** [comment]
Curiosamente, o CMP nunca deixou de ser calculado no script de acessibilidade. Ele só não era selecionado no script `05.1` quando a gente exporta a base de dados.
O commit https://github.com/ipeaGIT/acesso_oport/commit/462779976633f4c153e52cdb2c5cd24afc101a01 agora inclui o CMP pra exportar a base.

**Comment by rafapereirabr** [comment]
Pô, essa foi fácil ;)
