### ISSUE TITLE
Calcular acessibilidade tanto para o total quanto para a proporção de atividades

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#93]
Atualmente, estamos calculando somente a proporção das atividades (em relação ao total da cidade) que são acessadas. 
Seria interessante também incorporar variáveis com o total de atividades.
A sigla das variaveis está no formato `CMATT30` (indicador de acessibilidade, atividade e time threshold). Sugiro colocar um suffixo (T para total, P para proporcional) no final, ficando `CMATT30T` e `CMATT30P`

**Comment by rafapereirabr** [comment]
hm..... Algo para discutir.... Tem alguns pros e contras para considerarmos.

**Comment by rafapereirabr** [comment]
Rapaz, to pensando aqui, to achando melhor colocarmos todos indicadores  como valor absoluto. Se a pessoa quizer o numero relativo ela calcula por conta própria

**Comment by mvpsaraiva** [comment]
> Rapaz, to pensando aqui, to achando melhor colocarmos todos indicadores como valor absoluto. Se a pessoa quizer o numero relativo ela calcula por conta própria

Mas pra saber isso, é preciso saber o número total de empregos na cidade, certo? Vamos incluir essa informação nas próximas rodadas do projeto?

**Comment by kauebraga** [comment]
Decidimos incluir o total, ai se a pessoa quiser pode calcular o proporcional com as atividades nos hexagonos.

**Comment by rafapereirabr** [comment]
> > Rapaz, to pensando aqui, to achando melhor colocarmos todos indicadores como valor absoluto. Se a pessoa quizer o numero relativo ela calcula por conta própria
> 
> Mas pra saber isso, é preciso saber o número total de empregos na cidade, certo? Vamos incluir essa informação nas próximas rodadas do projeto?

sim, nessa proxima rodada a gente vai divulgar o numero de empregos em cada hexagono tmb

**Comment by kauebraga** [comment]
Ficamos com o total, somente!
