### ISSUE TITLE
Propor divisão e nomeclatura do arquivo final da base de dados

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#94]
A medida que a base de dados final vai aumentando, acho interessante a gente discutir uma nova estrutura de divisão.
Minha sugestão inicial é:
- 1 arquivo com a quantidade de atividades (saúde educação etc);
- 1 arquivo com acessibilidade para TP;
- 1 arquivo com acessibilidade para modos ativos

**Comment by rafapereirabr** [comment]
A estrutura que estamos usando no [aopdata](https://github.com/ipeaGIT/aopdata/) é essa aqui, com um arquivo separado para:
- populacao e dados socioeconomicos
- atividades / uso do solo
- acessibilidade (um arquivo separado para cada modo)
  - a pé
  - bicicleta
  - transporte publico

**Comment by kauebraga** [comment]
### Estrutura final:
- 1 arquivo com dados socioeconômicos e atividades (saúde educação etc);
- 1 arquivo com acessibilidade para TP (quando disponível) + carro;
- 1 arquivo com acessibilidade para modos ativos.

### As mudanças na nomenclatura das variáveis
**dados socioeconômicos e atividades**:
- P006 e P007: população de mulheres e homens, respectivamente;
- P10 a P16: população por idade;
- M001 a M004: quantidade de matrículas (total, ensino infantil, fundamental e médio);
- C001: quantidade de CRAS.

**dados de acessibilidade**:
Agora, vão ser disponibilizados as estimativas de **acessibilidade passiva** (CMP). A nomenclatura vai seguir a mesma lógica do CMA:
- CMPPT: acessibilidade passiva de população total;
- CMPPH: acessibilidade passiva de população de homens;
- CMPPH: acessibilidade passiva de população de mulheres;
- CMPPB, CMPPI, CMPPN, CMPPA: acessibilidade passiva de população por cor;
- CMPI00a05, CMPI06a14, CMPI15a18, CMPI19a24, CMPI25a39,CMPI40a69, CMPI70: acessibilidade passiva de população por idade.
