### ISSUE TITLE
fix h3 cells with problematic routing using h3jsr::get_kring()

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/acesso_oport#96]
- For each problematic h3 cell, determine the non-problematic neighbor cells using `h3jsr::get_kring()`
- Impute to problematic h3 cell the average travel times to and from its non-problematic neighboring cells

**Comment by kauebraga** [comment]
The new correction now has some extra steps. Overall:
* Identify problematic hex (1. weren't rooted by OTP; 2. can't access or be accessed by more than 10 other hex)
* For each problematic hex:
    *  Identify its level 3 neighbors. That would be 37 hex;
    * Filter only the neighbors that are not problematic;
    * Filter only the neighbors that are included in the original ttmatrix (some hex may be located outside the city, or weren't rooted in OTP because we didn't rooted hex without population/activities);
    * Out this result, select the 10 closest.
    * Now the correction has to be made for both the origin and the destination of each problematic hex (next 3 steps). 
    * Filter the neighbors in the original ttmatrix;
    * Substitute the values identifying the neighbors with the value of the problematic hex;
    * Group by origin, dest, mode, pico and calculate the mean of the travel time;
    * This will result in two corrected ttmatrix, one for the origin and other for the destination. Bind them.
* Bind the result of the previous steps (for all the problematic hex) with the ttmatrix of the hex that are not problematic.

**Comment by kauebraga** [comment]
Updated here a00b679d705e6629a227f76620697032aa143ed2

**Comment by kauebraga** [comment]
Done at script https://github.com/ipeaGIT/acesso_oport/blob/0db45aae92d1ec6506201a279e6d595db09a56bf/R/04.5-corrigir_ttmatrix.R#L109

**Comment by rafapereirabr** [comment]
Great. Just remember to add this info to the accessibility methods/data paper
