### ISSUE TITLE
Ajustar calculo do BFCA para pegar populacoes de interesse

### ISSUE THREAD

**Issue by kauebraga** [ipeaGIT/acesso_oport#99]

**Comment by kauebraga** [comment]
Tem um desencontro entre as idades que definimos para compor as variaveis la atras, com as idades "oficiais" se espera que os estudantes estejam em cada etapa de ensino.

As idades por etapa de ensino sao (fonte: https://pt.wikipedia.org/wiki/Idade_escolar): 
- educacao infantil: pop de 0 a 6 anos;
- educacao fund.: pop de 6 a 15 anos;
- educacao media: pop de 15 a 18 anos.

As nossas classes sao `c("idade_0a5", "idade_6a14", "idade_15a18", 'idade_19a24')`.
Tentando encaixar as classes, deixando uma folga, essas foram as classes definidas:
- educacao infantil: `idade_0a5`. Nesse caso, fica faltando a idade de 6 anos, porem se fosse incluir a proxima classe ia ter que acabar incluindo ate 14 anos de idade;
- educacao fundamental: `c("idade_6a14", "idade_15a18")`. Inclui todas as idades, alem de deixar uma folga pras pessoas de 16 e 17 anos de idade;
- educacao media: `c("idade_15a18", "idade_19a24")`. Inclui todas as idades e ainda deixar uma folga para pessoas de 19 a 24 anos. 
- educaco total: `c("idade_0a5", "idade_6a14", "idade_15a18", 'idade_19a24')`. Pega todas as classes ate 24 anos.

Os maiores problemas sao 1) nao incluir quem tem 6 anos na educacao infantil e 2) a folga para a educacao media ir ate 24 anos, que pode ser muito.  Nao sei se vale a pena voltar atras nos dados do censo e redefinir as variaveis de idade pra incorporarem mais classes.

**Comment by rafapereirabr** [comment]
> - educacao infantil: pop de 0 a 6 anos;
> - educacao fund.: pop de 6 a 15 anos;
> - educacao media: pop de 15 a 18 anos.

Me parece que nosso recorte de idade casa direitinho. Pelo o que eu entendi, essa classificação aí usa categoria fecharda à direita. tanto que a idade de '6' anos aparece na primeira e na segunda categoria. Na prática, a primeira vai até 5 anos completos; a segunda categoria vai até 14 anos completos e assim por diante. Não ?

**Comment by kauebraga** [comment]
Verifiquei aqui nos dados do Censo e vc tem razão! No Censo tem a classificação para cada ano, então o "Pessoas com 5 anos de idade" inclui de 5 a 6. Acha que vale a pena incluir essas folgas (fundamental para ate 19 anos, por ex) ou nem?

**Comment by dhersz** [comment]
> Pelo o que eu entendi, essa classificação aí usa categoria fecharda à direita. tanto que a idade de '6' anos aparece na primeira e na segunda categoria. Na prática, a primeira vai até 5 anos completos; a segunda categoria vai até 14 anos completos e assim por diante. Não ?

> No Censo tem a classificação para cada ano, então o "Pessoas com 5 anos de idade" inclui de 5 a 6.

Me parece que é fechada à esquerda e aberta à direita, [0, 6), [6, 15) e [15, 18). A `idade_0a5` então inclui de 0 até 6 não-completos. Pelo que entendi já é assim que tá o código, é mais um comentário.

**Comment by rafapereirabr** [comment]
> Verifiquei aqui nos dados do Censo e vc tem razão! No Censo tem a classificação para cada ano, então o "Pessoas com 5 anos de idade" inclui de 5 a 6. Acha que vale a pena incluir essas folgas (fundamental para ate 19 anos, por ex) ou nem?

eu nao incluiria as folgas nao

**Comment by kauebraga** [comment]
feito aqui https://github.com/ipeaGIT/acesso_oport/commit/0c49f27146c8656a8b94ebd4ef7781d7e8ce5006 sem folgas

**Comment by rafapereirabr** [comment]
podemos fechar esse aqui?
